# Nginx kullanarak statik dosyaları sunacağız
FROM nginx:alpine

# index.html dosyasını Nginx'in varsayılan klasörüne kopyala
COPY index.html /usr/share/nginx/html/index.html

# 80 portunu dışarı aç
EXPOSE 80